---
- hosts: all
  vars:
    - user: '{{ ansible_user_id }}'
  become: true # makes me root
  gather_facts: false
  # vars_files:
  #   - vars/default.yml

  tasks:
    - name: Install microk8s
      snap:
        name: microk8s
        classic: yes